vim.pack.add({
    "https://github.com/nvim-lua/plenary.nvim",
    { src = "https://github.com/theprimeagen/harpoon", name = "harpoon", version = "harpoon2" },
})

local harpoon = require("harpoon")
harpoon:setup({ settings = { save_on_toggle = true } })
harpoon:extend({
    UI_CREATE = function(cx)
        vim.keymap.set("n", "<C-v>", function()
            harpoon.ui:select_menu_item({ vsplit = true })
        end, { buffer = cx.bufnr })
        vim.keymap.set("n", "<C-x>", function()
            harpoon.ui:select_menu_item({ split = true })
        end, { buffer = cx.bufnr })
        vim.keymap.set("n", "<C-t>", function()
            harpoon.ui:select_menu_item({ tabedit = true })
        end, { buffer = cx.bufnr })
    end,
})

vim.keymap.set("n", "<leader>a", function()
    harpoon:list():add()
end, { desc = "Harpoon Add Mark File" })
vim.keymap.set("n", "<C-e>", function()
    harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Harpoon Toggle Quick Menu" })
vim.keymap.set("n", "<leader>1", function()
    harpoon:list():select(1)
end, { desc = "Harpoon File 1" })
vim.keymap.set("n", "<leader>2", function()
    harpoon:list():select(2)
end, { desc = "Harpoon File 2" })
vim.keymap.set("n", "<leader>3", function()
    harpoon:list():select(3)
end, { desc = "Harpoon File 3" })
vim.keymap.set("n", "<leader>4", function()
    harpoon:list():select(4)
end, { desc = "Harpoon File 4" })
vim.keymap.set("n", "<leader>5", function()
    harpoon:list():select(5)
end, { desc = "Harpoon File 5" })
